# Generated by Django 5.0.3 on 2024-03-21 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_order_options_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.AddField(
            model_name='product',
            name='ordered_quantity',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
