# Generated by Django 5.0.3 on 2024-03-22 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('IN PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='in_progress', max_length=20),
        ),
    ]
